pipeline {
    agent { label 'master' }

    stages {
        stage('Test') {
            steps {
                dir("build_java") {
                    sh "mvn clean compile test"
                    echo "Finished testing"
                }
            }
        }

        stage('Build Application') {
            steps {
                dir("build_java") {
                    sh "mvn -f pom.xml clean install -Dmaven.test.skip=true"
                    sh "tree"
                }
            }
        }

        stage('Create Docker Image') {
            steps {
                echo "Creating Docker image"
                // Aquí puedes agregar más pasos si es necesario
            }
        }
    }
}
