pipeline {
    agent any
    tools {
        maven 'Maven 3.6.3' // Asegúrate de que el nombre coincide con la configuración en Jenkins
    }
    //{ label 'master'}

        stages {
 
            stage ('test') {
                steps {
                  dir("build_java"){
                        sh "mvn clean compile test"
                      echo "mvn clean compile test"
                  }
                   
                   
                }
            }

            stage ('Build application') {
                steps {
                    dir("build_java"){

                        echo "mvn -f pom.xml clean install -Dmaven.test.skip=true"
                        echo "tree"
                    }   
                }
            }
  
            stage ('Create docker image') {
                steps {
                 echo "creando docker"
                }

            }
        }
}
